class Config:
    DATA = "data/"
    RAW = DATA + "raw/vllm-0.10.1"
    PROCESSED = DATA + "processed/"
    CHUNKS_PATH = PROCESSED + "chunks/chunks.json"
    CHROMA_PATH = PROCESSED + "chroma"
    OUTPUT = "output/"
    SEARCH_PATH = DATA + OUTPUT + "search_results"
    ANSWER_PATH = DATA + OUTPUT + "search_results_and_answer"
    BM25_PATH = PROCESSED + "bm25_index"
    DOCS_EM_MODEL = "nomic-embed-text"
    CODE_EM_MODEL = "nomic-embed-code"
    QWEN = "ollama/qwen3:0.6b"
    API_BASE = "http://localhost:11434"
