class Config:
    DATA = "data/"
    RAW = DATA + "raw/vllm-0.10.1"
    PROCESSED = DATA + "processed/"
    CHUNKS_PATH = PROCESSED + "chunks/chunks.json"
    CHROMA_PATH = PROCESSED + "chroma"
    OUTPUT = DATA + "output/"
    SEARCH_PATH = OUTPUT + "search_results"
    ANSWER_PATH = OUTPUT + "search_results_and_answer"
    BM25_PATH = PROCESSED + "bm25_index"
    MODEL = "ollama/qwen3:0.6b"
    EMBEDDING_MODEL = "all-minilm:l6-v2"
    # EMBEDDING_MODEL = "nomic-embed-text"
    API_BASE = "http://localhost:11434"
    SINGLE_QUERY = "single_query.json"
    SIDE_CHUNKS_PATH = PROCESSED + "chunks/side.json"
    MANIFEST = "data/.manifest"
